# Generated by Django 4.0.1 on 2022-02-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0008_remove_user_created_at_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/UsersUploads/'),
        ),
    ]
