# Generated by Django 4.0.1 on 2022-02-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0009_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='UsersUploads/defaultUserImage.png', null=True, upload_to='UsersUploads/'),
        ),
    ]
