# Generated by Django 4.0.1 on 2022-02-04 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Greenhouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('password', models.CharField(default='e8UwoFv', max_length=10)),
                ('cultivation_type', models.CharField(max_length=120)),
                ('water_tank_size', models.FloatField()),
                ('number_of_crops', models.IntegerField()),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('image', models.ImageField(upload_to='GreenhouseUploads/')),
                ('frame_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
