# Generated by Django 4.0.1 on 2022-02-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenhousesApp', '0003_alter_greenhouse_password_alter_greenhouse_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='1bSV0bC', max_length=10),
        ),
    ]
