# Generated by Django 4.0.1 on 2022-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantsApp', '0001_initial'),
        ('GreenhousesApp', '0004_greenhouse_is_active_alter_greenhouse_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='plants',
            field=models.ManyToManyField(related_name='greenhouse_plant', to='PlantsApp.Plants'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='2xYbyHm', max_length=10),
        ),
    ]
