# Generated by Django 4.0.1 on 2022-02-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenhousesApp', '0005_greenhouse_plants_alter_greenhouse_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='WJAbQX0', max_length=10),
        ),
    ]
