# Generated by Django 4.0.1 on 2022-02-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantsApp', '0004_rename_is_suppoted_plant_is_supported'),
        ('GreenhousesApp', '0014_alter_greenhouse_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='riZ1Fpo', max_length=10),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='plants',
            field=models.ManyToManyField(null=True, related_name='greenhouse_plant', to='PlantsApp.Plant'),
        ),
    ]
