# Generated by Django 4.0.1 on 2022-02-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GreenhousesApp', '0016_greenhouse_actuators_greenhouse_sensors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greenhouse',
            name='password',
            field=models.CharField(default='GKYySVS', max_length=10),
        ),
    ]
