# Generated by Django 4.0.1 on 2022-02-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenhousesApp', '0006_alter_greenhouse_password'),
        ('PlantsApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
