# Generated by Django 4.0.1 on 2022-02-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlantsApp', '0002_rename_plants_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='is_suppoted',
            field=models.BooleanField(default=False),
        ),
    ]
