# Generated by Django 4.0.1 on 2022-02-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlantsApp', '0003_plant_is_suppoted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='is_suppoted',
            new_name='is_supported',
        ),
    ]
