# Generated by Django 4.0.1 on 2022-02-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GreenhousesApp', '0017_alter_greenhouse_password'),
        ('HardwareApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actuators',
            new_name='Actuator',
        ),
        migrations.RenameModel(
            old_name='ActuatorsActions',
            new_name='ActuatorsAction',
        ),
        migrations.RenameModel(
            old_name='Sensors',
            new_name='Sensor',
        ),
        migrations.RenameModel(
            old_name='SensorValues',
            new_name='SensorValue',
        ),
    ]
