# Generated by Django 4.0.1 on 2022-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareApp', '0002_rename_actuators_actuator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actuator',
            name='image',
            field=models.ImageField(default=None, upload_to='HardwareUploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='image',
            field=models.ImageField(default=None, upload_to='HardwareUploads/'),
            preserve_default=False,
        ),
    ]
