# Generated by Django 4.0.1 on 2022-02-09 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareApp', '0006_alter_actuator_description_alter_sensor_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator',
            name='position',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='position',
        ),
    ]
