# Generated by Django 4.0.1 on 2022-02-09 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareApp', '0007_remove_actuator_position_remove_sensor_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='actuator_type',
            new_name='messure',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor_type',
            new_name='messure',
        ),
    ]
