# Generated by Django 4.0.1 on 2022-02-09 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HardwareApp', '0008_rename_actuator_type_actuator_messure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actuator',
            old_name='messure',
            new_name='action',
        ),
    ]
